# features.yml: paths and parameters for the features
---
host:
    dna: resources/reference/chrX_sub.fa.gz
    gtf: resources/reference/chrX_sub.gtf.gz

mags: resources/mags_mock.fa.gz

kraken2_databases:
    mock: resources/kraken_mock
